env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=60
jobs:
  build:
    defaults:
      run:
        shell: bash
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      if: runner.os == 'macos'
      name: Setup docker (missing on MacOS)
      run: 'brew install docker

        colima start

        '
    - continue-on-error: true
      env:
        SEDONA_VERSION: ${{ matrix.sedona }}
        SPARK_VERSION: ${{ matrix.spark }}
      run: ./docker/sedona-spark-jupyterlab/build.sh ${SPARK_VERSION} ${SEDONA_VERSION}
    strategy:
      fail-fast: true
      matrix:
        include:
        - sedona: 1.4.1
          spark: 3.4.1
        - sedona: latest
          spark: 3.4.1
        - sedona: latest
          spark: 3.3.2
        os:
        - ubuntu-latest
        - macos-latest
name: Docker build
on:
  repository_dispatch:
    types: trigger-ga___docker-build.yml
permissions:
  contents: read
