jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '8'
    - continue-on-error: true
      run: sudo apt-get remove scala-library scala
    - continue-on-error: true
      run: sudo wget www.scala-lang.org/files/archive/scala-2.12.11.deb
    - continue-on-error: true
      run: sudo dpkg -i scala-2.12.11.deb
    - continue-on-error: true
      run: scala -version
    - continue-on-error: true
      run: echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
    - continue-on-error: true
      run: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
    - continue-on-error: true
      run: sudo apt-get update
    - continue-on-error: true
      run: sudo apt-get install sbt
    - continue-on-error: true
      name: Cache SBT
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
        path: '~/.ivy2/cache

          ~/.sbt

          '
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      env:
        SEDONA_VERSION: ${{ matrix.sedona }}
        SPARK_COMPAT_VERSION: ${{ matrix.spark-compat }}
        SPARK_VERSION: ${{ matrix.spark }}
      run: (cd examples/spark-sql;mvn clean install -Dspark.version=${SPARK_VERSION}
        -Dspark.compat.version=${SPARK_COMPAT_VERSION} -Dsedona.version=${SEDONA_VERSION};java
        -jar target/sedona-spark-example-1.0.0.jar)
    - continue-on-error: true
      run: (cd examples/flink-sql;mvn clean install;java -jar target/sedona-flink-example-1.0.0.jar)
    strategy:
      fail-fast: false
      matrix:
        include:
        - sedona: 1.5.1
          spark: 3.5.0
          spark-compat: '3.5'
        - sedona: 1.5.1
          spark: 3.4.2
          spark-compat: '3.4'
        - sedona: 1.5.1
          spark: 3.3.4
          spark-compat: '3.0'
name: Example project build
on:
  repository_dispatch:
    types: trigger-ga___example.yml
permissions:
  contents: read
