env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=60
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      uses: actions/setup-python@v5
      with:
        python-version: '3.7'
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      env:
        SCALA_VERSION: ${{ matrix.scala }}
        SKIP_TESTS: ${{ matrix.skipTests }}
        SPARK_VERSION: ${{ matrix.spark }}
      run: "SPARK_COMPAT_VERSION=\"3.0\"\nif [ ${SPARK_VERSION:2:1} -gt \"3\" ]; then\n\
        \  SPARK_COMPAT_VERSION=${SPARK_VERSION:0:3}\nfi\nmvn -q clean install -Dspark=${SPARK_COMPAT_VERSION}\
        \ -Dscala=${SCALA_VERSION:0:4} -Dspark.version=${SPARK_VERSION} ${SKIP_TESTS}\n"
    - continue-on-error: true
      run: mkdir staging
    - continue-on-error: true
      run: cp spark-shaded/target/sedona-*.jar staging
    - continue-on-error: true
      run: '[ -d "flink-shaded/target/" ] && cp flink-shaded/target/sedona-*.jar staging
        2>/dev/null || true

        '
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: generated-jars ${{ matrix.spark }} ${{ matrix.scala }} ${{ matrix.jdk
          }}
        path: staging
    strategy:
      fail-fast: true
      matrix:
        include:
        - jdk: '8'
          scala: 2.13.8
          skipTests: ''
          spark: 3.5.0
        - jdk: '8'
          scala: 2.12.15
          skipTests: ''
          spark: 3.5.0
        - jdk: '11'
          scala: 2.12.15
          skipTests: ''
          spark: 3.5.0
        - jdk: '8'
          scala: 2.13.8
          skipTests: ''
          spark: 3.4.0
        - jdk: '8'
          scala: 2.12.15
          skipTests: ''
          spark: 3.4.0
        - jdk: '11'
          scala: 2.12.15
          skipTests: ''
          spark: 3.4.0
        - jdk: '8'
          scala: 2.12.15
          skipTests: ''
          spark: 3.3.0
        - jdk: '8'
          scala: 2.12.15
          skipTests: ''
          spark: 3.2.3
        - jdk: '8'
          scala: 2.12.15
          skipTests: ''
          spark: 3.1.2
        - jdk: '8'
          scala: 2.12.15
          skipTests: ''
          spark: 3.0.3
name: Scala and Java build
on:
  repository_dispatch:
    types: trigger-ga___java.yml
permissions:
  contents: read
