jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout ${{ github.ref }} ( ${{ github.sha }} )
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-python@v5
      with:
        architecture: x64
        python-version: 3.x
    - continue-on-error: true
      name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install pre-commit

        '
    - continue-on-error: true
      name: set PY
      run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
        path: ~/.cache/pre-commit
    - continue-on-error: true
      name: Run pre-commit
      run: pre-commit run --all-files
name: Lint
on:
  repository_dispatch:
    types: trigger-ga___lint.yml
permissions:
  contents: read
