jobs:
  build:
    defaults:
      run:
        shell: bash
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - continue-on-error: true
      name: Install pipenv
      run: pip install -U pipenv
    - continue-on-error: true
      name: Install dependencies
      run: 'cd python

        pipenv --python ${{ matrix.python }}

        pipenv install --dev

        '
    - continue-on-error: true
      name: Build extension
      run: 'cd python

        pipenv run python setup.py build_ext --inplace

        '
    - continue-on-error: true
      name: Run tests
      run: 'cd python

        pipenv run pytest tests/utils/test_geomserde_speedup.py

        '
    - continue-on-error: true
      name: Run tests on Shapely 2.0
      run: 'cd python

        pipenv install shapely~=2.0

        pipenv run pytest tests/utils/test_geomserde_speedup.py

        '
    - continue-on-error: true
      if: ${{ matrix.python == '3.9' || matrix.python == '3.8' }}
      name: Run tests on Shapley 1.7
      run: 'cd python

        pipenv install shapely~=1.7

        pipenv run pytest tests/utils/test_geomserde_speedup.py

        '
    - continue-on-error: true
      name: Install from sdist
      run: 'cd python

        pipenv run python setup.py sdist

        pipenv run python -m pip install dist/apache-sedona-*.tar.gz

        '
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        python:
        - '3.10'
        - '3.9'
        - '3.8'
name: Python build extension
on:
  repository_dispatch:
    types: trigger-ga___python-extension.yml
permissions:
  contents: read
