jobs:
  build:
    defaults:
      run:
        shell: bash
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      if: runner.os == 'Linux'
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
    - continue-on-error: true
      env:
        CIBW_ARCHS_LINUX: x86_64 aarch64
        CIBW_ARCHS_MACOS: x86_64 arm64
        CIBW_ARCHS_WINDOWS: AMD64 ARM64
        CIBW_SKIP: pp* *musl*
      name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      with:
        package-dir: python
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
name: Python build wheels
on:
  repository_dispatch:
    types: trigger-ga___python-wheel.yml
